### ISSUE TITLE
FEAT: Remove hardcoded paths

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmemkv-java#103]
# FEAT: parametrize Java code from Maven pom files

## Rationale

Removing hardcoded values from Java code

## Description

There is possibility to use Maven properties in Java code and avoiding passing paths separately (in Java code and POM files).

## API Changes

This enhancement will not change API, just internal implementation

## Implementation details

[This is the example](https://stackoverflow.com/questions/11500533/access-maven-properties-defined-in-the-pom)

**Comment by lukaszstolarczuk** [comment]
We've got those hardcoded paths in tests, and it is now fixed (see README for setting custom testing path).
