### ISSUE TITLE
Remove the UTF-8 encoding requirement

### ISSUE THREAD

**Issue by annamarcink** [pmem/pmemkv-java#14]
Without the UTF-8 setting failures occur in tests:

[ERROR] Failures: 
[ERROR]   KVEngineTest.putsUtf8ValueTest:207 Expected '? means to remember, note, record' to be equal '? means to remember, note, record'
[ERROR]   KVEngineTest.usesAllAboveTest:342 Expected 'BB,BC,' to be equal 'BB,BC,?!,'
[ERROR]   KVEngineTest.usesAllBelowTest:370 Expected '?!,A,AB,AC,' to be equal 'A,AB,AC,'
[ERROR]   KVEngineTest.usesAllBetweenTest:402 Expected '' to be equal 'BB,BC,?!,'
[ERROR]   KVEngineTest.usesAllTest:316 Expected '<1>,<2>,<?!>,' to be equal '<1>,<2>,<?!>,'
[ERROR]   KVEngineTest.usesEachAboveTest:511 Expected 'BB,5|BC,6|' to be equal 'BB,5|BC,6|?!,RR|'
[ERROR]   KVEngineTest.usesEachBelowTest:541 Expected '?!,RR|A,1|AB,2|' to be equal 'A,1|AB,2|'
[ERROR]   KVEngineTest.usesEachBetweenTest:576 Expected '' to be equal 'BB,5|BC,6|?!,RR|'
[ERROR]   KVEngineTest.usesEachTest:483 Expected '<1>,<one>|<2>,<two>|<?!>,<RR>|' to be equal '<1>,<one>|<2>,<two>|<?!>,<RR>|'

**Comment by lukaszstolarczuk** [comment]
Fixed
