### ISSUE TITLE
Add test with custom exception throwing for get_all

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv-java#157]
Similar to: https://github.com/pmem/pmemkv-java/blob/master/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L223

**Comment by KFilipek** [comment]
```java
auto status = engine->get_all(Callback_get_keys_buffer, &ctx);
if (status != pmem::kv::status::OK) PmemkvJavaException(env).ThrowException(status);
```
Should be changed with:
```java
auto status = engine->get_all(Callback_get_keys_buffer, &ctx);
if (env->ExceptionCheck() != JNI_TRUE)
    if (status != pmem::kv::status::OK) PmemkvJavaException(env).ThrowException(status);
```
When in callback body we get Java exception due to fail e.g. in NewByteBuffer, so if we want to propagate Java OOM exception we should avoid throwing pmemkv exception.
