### ISSUE TITLE
[pmemkv_open] An invalid argument was passed to create pmem kind; error code: -13

### ISSUE THREAD

**Issue by tomsun28** [pmem/pmemkv-java#179]
# QUESTION: 

## Details

Hi, I am a newer using pmemkv-java. Exception happen when init database, would you know what could be the cause, thanks.    

````
        database = new Database.Builder<PrimaryKey, ByteBuffer>("vsmap")
                    .setSize(10L << 20)
                    .setPath(filename)
                    .setKeyConverter(new PrimaryKeyConverter())
                    .setValueConverter(new ByteBufferConverter())
                    .setForceCreate(true)
                    .build();
````
exception: 
````
Exception in thread "collector-1-thread" io.pmem.pmemkv.InvalidArgumentException: [pmemkv_open] An invalid argument was passed to create pmem kind; error code: -13
	at io.pmem.pmemkv.Database.database_start(Native Method)
	at io.pmem.pmemkv.Database.<init>(Database.java:727)
	at io.pmem.pmemkv.Database.<init>(Database.java:32)
	at io.pmem.pmemkv.Database$Builder.build(Database.java:581)
````

version - 1.0.1 or 1.2.0

Thanks Again.

**Comment by KFilipek** [comment]
Hi,
Error you get is returned from Memkind library (underlying allocator for vsmap engine). `kind_wrapper_t` use memkind function: `memkind_create_pmem_with_config` and passes only `max_size` and `dir`, so the problem is here. 
From memkind.h:
`MEMKIND_PMEM_MIN_SIZE = (1024 * 1024 * 16)  /**<  The minimum size which allows to limit the file-backed memory partition */`
So, your size is not enough to fulfill allocator requirements for minimum PMEM kind, try more. Last thing is `setPath()`, in vsmap/memkind it should be an directory, not a file.

**Comment by tomsun28** [comment]
Thanks!

**Comment by KFilipek** [comment]
> Thanks!

If this solved your issue give us a feedback and please close the issue, otherwise we will support you.

**Comment by tomsun28** [comment]
@KFilipek thanks, it is work. I have an other question about ```cmap```.  when i use the ```cmap``` as database engine, the exception show:   

````
Exception in thread "collector-1-thread" io.pmem.pmemkv.WrongEngineNameException: [pmemkv_open] Unknown engine name "cmap". Available engines: blackhole, vsmap
	at io.pmem.pmemkv.Database.database_start(Native Method)
	at io.pmem.pmemkv.Database.<init>(Database.java:727)

````
version - 1.0.1 or 1.2.0

Is there only vsmap, blackhole as the storage engine? I see supports cmap by default in document.

**Comment by lukaszstolarczuk** [comment]
@tomsun28 , what version of `pmemkv` you're using?

And if you installed `pmemkv` from sources - did you manually disabled any engines? Each engine (during `pmemkv` installation) can be enabled/disabled using special flag (see [pmemkv's CMake file](https://github.com/pmem/pmemkv/blob/master/CMakeLists.txt#L34))

**Comment by tomsun28** [comment]
Hi, i use cloud services provided by others. Yesterday I reported that they did not answer me. I close this issue, and will feedback after I have an answer. Thanks.
