### ISSUE TITLE
How can I contribute to this codebase?

### ISSUE THREAD

**Issue by JerryYangSH** [pmem/pmemkv-java#30]
It looks I have no permission to pmem/pmemkv-java.git. How can I get the permission ? Thanks

**Comment by igchor** [comment]
Hello, we accept contribution through Pull Requests. Please look at: https://github.com/pmem/pmemkv-java/blob/master/CONTRIBUTING.md for guidelines.

**Comment by lukaszstolarczuk** [comment]
@JerryYangSH, did we resolve your issue?
If you have anything to add here or you have more questions please let us know :) If not, we'll close this issue.

**Comment by JerryYangSH** [comment]
@lukaszstolarczuk Thanks. I've done. Please close this one.
