### ISSUE TITLE
Data Serialization and Deserialization

### ISSUE THREAD

**Issue by ch2994** [pmem/pmemkv-java#95]
Hello I am new to pmemkv-java and I have a question. I am looking to create a kv-store with string as key and ByteBuffer as value. My question is do I need to serialize the data before putting them in the store? 

Thanks

**Comment by lukaszstolarczuk** [comment]
Hi,
See our examples - https://github.com/pmem/pmemkv-java/tree/master/examples - if your data can be converted/stored as a ByteBuffer then just use them as in our examples.
So basically, you don't have to serialize, but you can if you want (and then store them e.g. as a String).

If you have more questions, please follow up.

**Comment by karczex** [comment]
@ch2994 Your case is exactly one covered by https://github.com/pmem/pmemkv-java/blob/master/examples/MixedTypesExample.java  
ByteBufferConverter is part of API, for other types you need to define converter by yourself. 

This article may be helpful for you: https://pmem.io/2020/10/30/pmemkv-java-binding.html

**Comment by lukaszstolarczuk** [comment]
I hoped it answered your question. If you still have some comments on this topic please let us know (file a new issue if needed).
